























100%|███████████████████████████████████████████████████████████████████████████████████| 200/200 [00:49<00:00,  4.01it/s]
Traceback (most recent call last):
  File "mult.py", line 155, in <module>
    train_autoencoder()
  File "mult.py", line 135, in train_autoencoder
    restored_fill_data[i, j] = X_test_tensor[i, j]
IndexError: index 13 is out of bounds for axis 1 with size 11
0
7
0
9
0
10
0
13